# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  iosevka = {
    pname = "iosevka";
    version = "v33.2.2";
    src = fetchFromGitHub {
      owner = "be5invis";
      repo = "Iosevka";
      rev = "v33.2.2";
      fetchSubmodules = false;
      sha256 = "sha256-dhMTcceHru/uLHRY4eWzFV+73ckCBBnDlizP3iY5w5w=";
    };
  };
}
