[buildPlans.PragmasevkaSans]
family = "Pragmasevka-Sans"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
noLigation = true

  [buildPlans.PragmasevkaSans.variants]
  inherits = "ss08"
  [buildPlans.PragmasevkaSans.metricOverride]
  leading = 1080
  xHeight = 550

    [buildPlans.PragmasevkaSans.variants.design]
    three = "flat-top-serifless"
    zero = "slashed"
    capital-i = "short-serifed"
    capital-j = "serifless"
    f = "serifless"
    g = "double-storey-open"
    i = "zshaped"
    k = "diagonal-tailed-cursive-serifless"
    l = "serifed"
    r = "top-serifed"
    caret = "low"
    paren = "normal"
    brace = "straight"
    ampersand = "closed"
    percent = "rings-continuous-slash"

[buildPlans.PragmasevkaSans.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.PragmasevkaSans.weights.ExtraBold]
shape = 800
menu = 800
css = 800

[buildPlans.PragmasevkaSans.weights.Heavy]
shape = 900
menu = 900
css = 900

[buildPlans.PragmasevkaSans.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.PragmasevkaSans.slopes]
upright = "default.Upright"
italic = "default.Italic"
